config/routes.rb
Rails.application.routes.draw do
  resources :mesages
  resources :posts
  devise_for :users
  resources :users
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :post, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post, :date, :time, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, remote: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :post ,size: "50x6", style: 'resize: none' %>
  </div>

  <%= form.hidden_field :date ,value: Time.now.strftime("%Y-%m-%d")%>
  <%= form.hidden_field :time ,value: Time.now.strftime("%H:%M:%S")%>
  <%= form.hidden_field :user_id ,value: current_user.id%>

  <div class="actions">
    <%= form.submit 'Publicar' , style: 'width: 421px'%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
  <body style="background-color: pink;>
  <div style="height: auto">

    <div class="btn-group" style="position: fixed;top:0px;left: 0px;right: 0px; height: 40px; background-color: #FF00FF">
      <%= image_tag "icon.png",size: "50x50", style:'left: 10000px' %>
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="margin-left: auto; right: 10px;"></button>
      <ul class="dropdown-menu">
        <% if policy(current_user).index? %>
            <li><%= link_to 'Contas', users_path ,style:'text-decoration:none;'%></li>
            <li><%= link_to 'Conta', current_user ,style:'text-decoration:none;'%></li>
        <% else %>
          <li><%= link_to 'Conta', current_user ,style:'text-decoration:none;'%></li>
        <% end %>
        <li><%= link_to "Sair", destroy_user_session_path, method: :delete ,style:'text-decoration:none;'%></li>
      </ul>
  
    </div>
    <div class="userInformation" style="position: fixed;top:50px;left: 10px;right: 0px;width: 250px;">
      <p><%= image_tag current_user.avatar.url(:show) %></p> 
      <h3><%= current_user.name + ' ' + current_user.lastName%></h3>
      <button type="button" class="btn btn-primary"><%= link_to 'Mensagens', mesages_path ,style:'text-decoration:none;'%></button>
    </div>
    <div style="position: relative; left: 250px; top: 30px;width: 500px; bottom: 0px; justify-content: center; align-items: left; display: flex; flex-direction: column; ">
      <button type="button" class="btn btn-primary" style="margin-left: auto; align-items: right; position: static;"><%= link_to 'Publicar', new_post_path %></button>
    
    <% @posts.each do |post| %>
      <div class="post" style="min-height: 50px; height: auto; background-color: white;">
          <p><%= "Spotted" %></p>
          <p><%= post.date.strftime("%d de %m de %Y") + ' às ' + post.time.strftime("%H:%M") %></p>
          <!-- <td><%= link_to 'Edit', edit_post_path(post) %></td> -->
          <p><%= post.post %>
          <%= link_to "Enviar mensagem", new_mesage_path(:destUser => post.user.id, :sentUser => current_user.id) %> 
          <% if %>
          <%= link_to 'Excluir', post, method: :delete, data: { confirm: 'Você tem certeza que deseja excluir esse post?' } %>
          <% end %>
           </p>
      </div>
      <div style="height: 10px"></div>
    <% end %>
    </div>
  </div>
<br>

</body>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post.post %>
</p>

<p>
  <strong>Date:</strong>
  <%= @post.date.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Time:</strong>
  <%= @post.time.strftime("%H:%M:%S") %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>