config/routes.rb
Rails.application.routes.draw do
  resources :mesages
  resources :posts
  devise_for :users
  resources :users
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mesage.rb
class Mesage < ApplicationRecord
  belongs_to :sentUser
  belongs_to :destUser
end

app/controllers/mesages_controller.rb
class MesagesController < ApplicationController
  before_action :set_mesage, only: [:show, :edit, :update, :destroy]

  # GET /mesages
  # GET /mesages.json
  def index
    @mesages = Mesage.all
  end

  # GET /mesages/1
  # GET /mesages/1.json
  def show
  end

  # GET /mesages/new
  def new
    @mesage = Mesage.new
    @destUser = params[:destUser]
    @sentUser = params[:sentUser]
  end

  # GET /mesages/1/edit
  def edit
  end

  # POST /mesages
  # POST /mesages.json
  def create
    @mesage = Mesage.new(mesage_params)

    respond_to do |format|
      if @mesage.save
        format.html { redirect_to @mesage, notice: 'Mesage was successfully created.' }
        format.json { render :show, status: :created, location: @mesage }
      else
        format.html { render :new }
        format.json { render json: @mesage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mesages/1
  # PATCH/PUT /mesages/1.json
  def update
    respond_to do |format|
      if @mesage.update(mesage_params)
        format.html { redirect_to @mesage, notice: 'Mesage was successfully updated.' }
        format.json { render :show, status: :ok, location: @mesage }
      else
        format.html { render :edit }
        format.json { render json: @mesage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mesages/1
  # DELETE /mesages/1.json
  def destroy
    @mesage.destroy
    respond_to do |format|
      format.html { redirect_to mesages_url, notice: 'Mesage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mesage
      @mesage = Mesage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mesage_params
      params.require(:mesage).permit(:mesage, :sentUser_id, :destUser_id, :dataSent, :timeSent)
    end
end

app/helpers/mesages_helper.rb
module MesagesHelper
end

app/views/mesages/_form.html.erb
<%= form_with(model: mesage, local: true) do |form| %>
  <% if mesage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mesage.errors.count, "error") %> prohibited this mesage from being saved:</h2>

      <ul>
      <% mesage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mesage %><br />
    <%= form.text_area :mesage %>
  </div>
  
  <%= form.hidden_field :dataSent ,value: Time.now.strftime("%Y-%m-%d")%>
  <%= form.hidden_field :timeSent ,value: Time.now.strftime("%H:%M:%S")%>
  <%= form.hidden_field :destUser_id ,value: @destUser %>
  <%= form.hidden_field :sentUser_id ,value: @sentUser %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mesages/edit.html.erb
<h1>Editing Mesage</h1>

<%= render 'form', mesage: @mesage %>

<%= link_to 'Show', @mesage %> |
<%= link_to 'Back', mesages_path %>

app/views/mesages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mesages</h1>

<table>
  <thead>
    <tr>
      <th>Mesage</th>
      <th>Sentuser</th>
      <th>Destuser</th>
      <th>Datasent</th>
      <th>Timesent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mesages.each do |mesage| %>
      <tr>
        <td><%= mesage.mesage %></td>
        <td><%= mesage.sentUser %></td>
        <td><%= mesage.destUser %></td>
        <td><%= mesage.dataSent %></td>
        <td><%= mesage.timeSent %></td>
        <td><%= link_to 'Show', mesage %></td>
        <td><%= link_to 'Edit', edit_mesage_path(mesage) %></td>
        <td><%= link_to 'Destroy', mesage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mesage', new_mesage_path %>

app/views/mesages/new.html.erb
<h1>New Mesage</h1>

<%= render 'form', mesage: @mesage %>

<%= link_to 'Back', posts_path %>

app/views/mesages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mesage:</strong>
  <%= @mesage.mesage %>
</p>

<p>
  <strong>Sentuser:</strong>
  <%= @mesage.sentUser %>
</p>

<p>
  <strong>Destuser:</strong>
  <%= @mesage.destUser %>
</p>

<p>
  <strong>Datasent:</strong>
  <%= @mesage.dataSent %>
</p>

<p>
  <strong>Timesent:</strong>
  <%= @mesage.timeSent %>
</p>

<%= link_to 'Edit', edit_mesage_path(@mesage) %> |
<%= link_to 'Back', mesages_path %>